services:
  - type: web
    name: metabase
    env: docker
    repo: https://github.com/kiendt07/metabase-render-demo.git # optional
    plan: starter # ensure that metabase has at least 2GB of RAM (defaults to starter)
    autoDeploy: false